spring:
  application:
    name: ConsumerService
server:
  port: 8091
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:9091/eureka
#spring.cloud.config.uri=http://localhost:9090
#eureka.client.serviceUrl.defaultZone: http://localhost:9091/eureka
#eureka.client.registerWithEureka: true
#eureka.client.fetchRegistry: true
instance:
  hostname: localhost